### ISSUE TITLE
Op cast failure for EXISTS

### ISSUE THREAD

**Issue by jadbox** [adilbaig/Tiny-Redis#11]
Calls like the below are getting a dmd error saying it can't do Op cast boolean with Response object.
DMD: DMD64 D Compiler v2.066.1

```if(redis.send("EXISTS", fruits)) {}```

**Comment by adilbaig** [comment]
Hi @jadbox,

Thanks for reporting this. I've verified the above works on DMD64 v2.066.1. See example.d line 106. Pull the lastest master branch and run 'make example'. You should see "'tinyredis' exists" in the output

**Comment by adilbaig** [comment]
Hey @jadbox ,

I closed this issue without waiting for a comment from your end. Do ping back, whether it works or not. I'm happy to help.

Thanks
