### ISSUE TITLE
Test cases fail on older gdc versions (4.9.0, dmdfe 2.065)

### ISSUE THREAD

**Issue by truedat101** [adilbaig/Tiny-Redis#26]
```
14:10 $ dub test --compiler=gdc
Generating test runner configuration '__test__default__' for 'default' (library).
Building tinyredis 2.1.0 configuration "__test__default__", build type unittest.
Running gdc...
source/tinyredis/collections/set.d:100: error: module primitives is in file 'std/range/primitives.d' which cannot be read
import path[0] = /mnt/lotsostuff/dev/tools/x86_64-gdcproject-linux-gnu/include/d/4.9.0/x86_64-unknown-linux-gnu
import path[1] = /mnt/lotsostuff/dev/tools/x86_64-gdcproject-linux-gnu/include/d/4.9.0
import path[2] = /mnt/lotsostuff/dev/repos/Tiny-Redis.git/source
FAIL .dub/build/__test__default__-unittest-linux.posix-x86_64-gdc_2065-C3639316B5C48C03D979CFC6A9132E22/ __test__default__ executable
Error executing command test: gdc failed with exit code 1.
```

It appears we don't have std.range.primitives in that earlier version, though it's hard to tell from the Dlang docs when std.range.primitives was introduced.  Because TinyRedis core doesn't rely on std.range.primitives, it would make sense to refactor the one test case using this, line 100-101 of set.d.

**Comment by truedat101** [comment]
Also affects:
```
dub test --compiler=gdc
Generating test runner configuration '__test__default__' for 'default' (library).
Building tinyredis 2.1.0 configuration "__test__default__", build type unittest.
Running gdc...
source/tinyredis/collections/set.d:126: error: module searching is in file 'std/algorithm/searching.d' which cannot be read
import path[0] = /mnt/lotsostuff/dev/tools/x86_64-gdcproject-linux-gnu/include/d/4.9.0/x86_64-unknown-linux-gnu
import path[1] = /mnt/lotsostuff/dev/tools/x86_64-gdcproject-linux-gnu/include/d/4.9.0
import path[2] = /mnt/lotsostuff/dev/repos/Tiny-Redis-iotone.git/source
FAIL .dub/build/__test__default__-unittest-linux.posix-x86_64-gdc_2065-C3639316B5C48C03D979CFC6A9132E22/ __test__default__ executable
Error executing command test: gdc failed with exit code 1.
```

related to std.algorithm.searching

**Comment by adilbaig** [comment]
@truedat101 - Older versions of dmd used a more top-level namespace. I'm not sure when they decided to split std.algo into multiple namespaces, so I'm taking a stab at this by using the more top-level namespace. You can see my code here : https://github.com/adilbaig/Tiny-Redis/tree/old-gdc-fix

Can you try this branch with your code? This is a more permanent fix.

**Comment by truedat101** [comment]
Interesting, I wish the d-docs included annotations for DMDFE versions so that one could easily know when a particular feature was introduced, as they do with Android docs, for example.  Maintaining legacy software is of course hard.

I'll try out the branch.  Thanks.

**Comment by truedat101** [comment]
Indeed that works with "old gdc".

**Comment by adilbaig** [comment]
Great. I've merged this into master.
