### ISSUE TITLE
Is there any way to close a redis connection?

### ISSUE THREAD

**Issue by dedupely** [adilbaig/Tiny-Redis#28]
I can't see it in the docs. Just wondering is this can be an issue.

**Comment by adilbaig** [comment]
That's a valid concern.

There isn't an explicit close method as the `Redis` object is useless
without it. The idea is to destroy the object and the connection destructor
will close itself.

I realize this is a blunt tool, no one has asked for a close/reconnect
method so far.

Adil

**Comment by dedupely** [comment]
Makes sense. Was just a bit worried, thinking like Postgres user. However, sounds good.

BTW, if the redis server restarts or stops half way through a process while a tinyredis connection is open, what happens? Just throws an error?

**Comment by adilbaig** [comment]
Yes, throws an Exception. 

This design is a bit dated, I don't like the fact that the connection is managed inside the object, it really should be passed outside in so disconnects can be handled properly in userland code.

Given that, an improvement would be to use UFCS style functions on a generic TCPSocket. The code would "look" the same, but you'd have access to all Socket methods.

**Comment by dedupely** [comment]
Well, I think this is okay for now. Thanks for the info. I'll close this thread.
