### ISSUE TITLE
Do not work with SCAN

### ISSUE THREAD

**Issue by moechofe** [adilbaig/Tiny-Redis#32]
When SCAN reach the end of the database, the process is stuck somewhere here: 
https://github.com/adilbaig/Tiny-Redis/blob/master/source/tinyredis/connection.d#L100
`buffer.length` = 0 and `MultiBulks.length` = 1

##### to reproduce
```d
import tinyredis;
import std.stdio; 
void main()
{
  auto c=new Redis();
  c.send("flushdb");
  auto r=c.send("scan",0);
  if(r.isArray)
    foreach(k,v; r.values[1].values)
      writefln("key: %s",v.value);
}
```

**Comment by adilbaig** [comment]
This is now fixed in master

````
auto c = new Redis();
 c.send("flushdb");
 auto r = c.send("scan", 0);
 writeln(r);
````

````
./test 
[0, []]
````
