### ISSUE TITLE
Dub release

### ISSUE THREAD

**Issue by o3o** [adilbaig/Tiny-Redis#36]
First of all thank you for your library.

Can you please release a new dub version that includes https://github.com/adilbaig/Tiny-Redis/issues/32 and https://github.com/adilbaig/Tiny-Redis/issues/35?

Thank you

**Comment by adilbaig** [comment]
Hey,

Thank you for bringing this to my attention. I've made a new release, and have triggered code.dlang to pick it up. I don't know how long it takes. In the meantime you can download tag v2.2.0 from Github to get going.

**Comment by o3o** [comment]
Thank you very much
