### ISSUE TITLE
Error and semver consideration

### ISSUE THREAD

**Issue by o3o** [adilbaig/Tiny-Redis#43]
I had version 2.2.1, upgraded to 2.3.1 and the compiler complains:

```
Error: no property `empty` for type `Response`, perhaps `import std.range;` is needed?
```
In my code the problem is here:
```
...
auto list = db.send("LRANGE", name, 0, stop);
if (!list.empty) {
   ... 
```
so, IMHO this is a [breaking change](https://semver.org/), you should increment version to 3.0.0 .... what do you think?

Thank you very much

**Comment by adilbaig** [comment]
Agreed. In this case, I recommend we make a small change before introducing a new version, so existing installations don't break silently.

Perhaps you would like to update `examples/example.d` with a snippet like the above?
