### ISSUE TITLE
binary strings

### ISSUE THREAD

**Issue by Laeeth** [adilbaig/Tiny-Redis#8]
Hi.

One of the nice things about redis is that strings can be binary.  This facilitates use with binary object serialisation using msgpack, for example.

I think you do not implement opCast for ubyte[], which is what would be needed for this purpose.

Am I missing something, or is it worth considering this enhancement?

Laeeth.

**Comment by adilbaig** [comment]
Hi @Laeeth ,

From your PR, it looks like you're just trying to cast the output to a `ubyte[]`. I can add that in.

**Comment by adilbaig** [comment]
Hi @Laeeth ,

I've pushed some changes to the `master` branch that allow you to cast a response to a `(u)byte[]` (tests included). Could you give it a shot and let me know if it works?
